package com.itextpdf.kernel.pdf;

public enum PageLabelNumberingStyleConstants {
    DECIMAL_ARABIC_NUMERALS, UPPERCASE_ROMAN_NUMERALS, LOWERCASE_ROMAN_NUMERALS, UPPERCASE_LETTERS, LOWERCASE_LETTERS
}
